
INSERT INTO [Financiero].[PLE_050100_txt_declarado]
           ([C1_Periodo]
           ,[C2_Cuo]
           ,[C3_Correlativo]
           ,[C4_Cuenta]
           ,[C5_UnidadOperacion]
           ,[C6_CentroCosto]
           ,[C7_MonedaOrigen]
           ,[C8_TipoDocumento]
           ,[C9_NumeroDocumento]
           ,[C10_TipoComprobante]
           ,[C11_Serie]
           ,[C12_Numero]
           ,[C13_FechaContable]
           ,[C14_FechaVencimiento]
           ,[C15_FechaDocumento]
           ,[C16_Glosa]
           ,[C17_GlosaReferencial]
           ,[C18_Debe]
           ,[C19_Haber]
           ,[C20_Estructura]
           ,[C21_Estado]

           ,[Compania]
           ,[IdCompania]
           ,[CodigoAnioPeriodo]
           ,[SistemaOrigen]
           ,[NumeroProceso])

SELECT 
      [Col1]
      ,[Col2]
      ,[Col3]
      ,[Col4]
      ,[Col5]
      ,[Col6]
      ,[Col7]
      ,[Col8]
      ,[Col9]
      ,[Col10]
      ,[Col11]
      ,[Col12]
      ,[Col13]
      ,[Col14]
      ,[Col15]
      ,[Col16]
      ,[Col17]
      ,[Col18]
      ,[Col19]
      ,[Col20]
      ,[Col21]

      ,CONCAT([IdCompania],[CodigoAnioPeriodo])
      ,[IdCompania]
      , [CodigoAnioPeriodo]
      , 'CONCAR'
      , 1
  FROM [Financiero].[SunatElectronicoTxtDeclarado]
  WHERE IdCompania = 32 AND CodigoAnioPeriodo = '201901' AND Codigo = '050100'