SELECT * FROM Configuracion.ViewTablaPLE WHERE Reporte = 'SITUACION FINANCIERA - CONCAR' AND Nivel = 2

SELECT * FROM Configuracion.ViewTablaPLE WHERE Reporte = 'SITUACION FINANCIERA - PLE' AND Nivel = 2
SELECT
    Codigo = '0' + LEFT(LE_CAMPO2,1) + '.0' + SUBSTRING(LE_CAMPO2,2,1) + '.' + RIGHT(RTRIM(LE_CAMPO2),2)
    , Descripcion = LE_DESCRIPCION
    , Clave = LE_CAMPO1
    , Campo2 = LE_CAMPO2, *
FROM produccion.enproyecdb.dbo.TB_TABLAS_LE L WITH (NOLOCK)
WHERE L.LE_CLAVE='34' and L.LE_PLAN='32' AND L.LE_EMPRESA='0001'





SELECT * FROM Configuracion.ViewTablaPLE WHERE Texto0 LIKE '%1D0302%'
--SELECT * FROM Configuracion.TablaPLE WHERE Id IN (5561)


SELECT L.LE_CAMPO1, P.PFORBAL FROM produccion.rsconcar.dbo.ct0032plem P  WITH (NOLOCK)
INNER JOIN produccion.enproyecdb.dbo.TB_TABLAS_LE L WITH (NOLOCK) ON L.LE_CLAVE='34' and L.LE_PLAN='32' AND  ISNULL(L.LE_CAMPO1,'')!='' AND L.LE_EMPRESA='0001' AND 
(LE_CAMPO2 = P.PFORBAL OR LE_CAMPO3 = P.PFORBAL OR LE_CAMPO4 = P.PFORBAL OR LE_CAMPO5 = P.PFORBAL OR LE_CAMPO6 = P.PFORBAL OR LE_CAMPO7 = P.PFORBAL OR LE_CAMPO8 = P.PFORBAL)





--INSERT INTO Configuracion.TablaPLE(Codigo, Descripcion, IdParent, Texto0)





SELECT 
    Codigo = P.PCUENTA
    ,Descripcion = P.PDESCRI
    ,CodigoParent = P.PFORBAL
    ,DescripcionParent = a.TDESCRI
    , p.*
FROM produccion.rsconcar.dbo.ct0032tage a
INNER JOIN produccion.RSCONCAR.dbo.ct0032plem p ON LTRIM(RTRIM(p.PFORBAL)) =  LTRIM(RTRIM(a.TCLAVE))
--LEFT JOIN Configuracion.ViewTablaPLE vp WITH (NOLOCK) ON RTRIM(vp.Codigo) = RTRIM(P.PCUENTA) COLLATE Modern_Spanish_CI_AS AND Reporte = 'SITUACION FINANCIERA - CONCAR'
WHERE a.TCOD = '10' -- AND vp.Id IS NULL

SELECT DISTINCT PFORBAL, PFORGYP, PLINGYP, PFORGNA, PFORRE1, PFOR01, PFOR02, PFOR03, PFOR04, PFOR05
FROM produccion.RSCONCAR.dbo.ct0032plem
WHERE LIKE 1D0109

SELECT * FROM produccion.RSCONCAR.dbo.ct0032plem

SELECT * FROM produccion.RSCONCAR.dbo.CTA04  WHERE TCLAVE IN (SELECT DISTINCT TCOD FROM produccion.rsconcar.dbo.ct0032tage)

SELECT DISTINCT TCOD FROM produccion.rsconcar.dbo.ct0032tage WHERE TCOD = '20'
20





  select codigo=left(TDESCRI,6) from produccion.rsconcar.dbo.ct0032tage where tcod = '55'                   
  union all                   
  select codigo=left(TDESCRI,6) from produccion.rsconcar.dbo.ct0032tage where tcod = '58'
  SELECT * FROM CTA04

  select * from produccion.rsconcar.dbo.ct0032tage where tcod = '10'
--SELECT * FROM [dbo].[CP0032CUBA] -- Cuenta Bancaria
--SELECT * FROM [dbo].[CT0032ANEX]
--SELECT * FROM [dbo].[CT0032ANEX]
--SELECT * FROM [dbo].[CT0032PLSU][dbo].[CT0032PLEM][dbo].[CT0032PLEM]

SELECT TOP 10 * FROM sys.all_objects WHERE   name LIKE 'CT0032%'


SELECT DISTINCT LEFT(TABLE_NAME,4) FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG = 'rsconcar' -- AND TABLE_NAME LIKE 'CT0084%23%'


SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG = 'rsconcar' AND TABLE_NAME LIKE 'CT%'


SELECT * FROM CT0032ANEX -- Anexos
SELECT * FROM CT0032CICA--
SELECT * FROM CT0032CIDE--
SELECT * FROM CT0032CONT21 --
SELECT * FROM CT0032DOCR -- Comprobante
SELECT * FROM CT0032PLEM -- Plan de cuentas
SELECT * FROM CT0032RUBM -- 
SELECT * FROM CT0032TAGE -- Tabla General
SELECT * FROM CT0032TRAE --
SELECT * FROM CTA04-- Indice de tablas




SELECT * FROM CTCAMB
SELECT * FROM CTCASF
SELECT * FROM CTCIAS
SELECT * FROM CTEJEM
SELECT * FROM CTEMPCOMC10
SELECT * FROM CTEMPR
SELECT * FROM CTFACT
SELECT * FROM CTFESC
SELECT * FROM CTFESD
SELECT * FROM CTFOES
SELECT * FROM CTSISPEN
SELECT * FROM CTTABE

